"""count Cell"""
from cell import Cell

print("Create object of cell")
cell1 = Cell(30)
cell2 = Cell(25)
cell3 = Cell(10)
cell4 = Cell(15)
cell5 = Cell(12)
print()
print("Sum")
print(cell1 + cell2)
print()
print("Subtraction")
print(cell2 - cell1)
print(cell4 - cell3)
print()
print("Multiply")
print(cell2 * cell1)
print()
print("Division")
print(cell1 / cell2)
print()
print("Organizing cells by row:")
print(cell5.make_order(5))
print(cell2.make_order(10))
